# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Jekyll Metro'
tagline:          'A Metro theme for Jekyll'
description:      'A Sample blog using Jekyll Metro'
url:              'http://fazoz.github.io'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/

# Author Details
author:         'Jake McGregor'
linkedin:       'https://ae.linkedin.com/in/olakara/'
twitter:        'https://twitter.com/fazoz'
facebook:       'https://www.facebook.com/olakara'
gplus:          'https://plus.google.com/u/0/+JakeMcGregor'

# Google Analytics
gahandler: 'UA-52149651-1'

# Disqus
disqushandler: 'testingblogo'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.7.9
